/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.LogIn;

import java.awt.event.ActionListener;

/**
 *
 * @author letu
 */
public class BossView extends javax.swing.JFrame {

    /**
     * Creates new form BossView
     */
    public BossView() {
        super("Boss Management");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        accountButton = new javax.swing.JButton();
        deliveryButton = new javax.swing.JButton();
        dealerButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/logo.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, -10, 220, 270);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Boss's Menu");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(410, 90, 370, 60);

        accountButton.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        accountButton.setForeground(new java.awt.Color(153, 153, 153));
        accountButton.setText("Account");
        accountButton.setBorder(null);
        accountButton.setBorderPainted(false);
        accountButton.setContentAreaFilled(false);
        accountButton.setFocusPainted(false);
        accountButton.setFocusable(false);
        jPanel1.add(accountButton);
        accountButton.setBounds(430, 250, 250, 50);

        deliveryButton.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        deliveryButton.setForeground(new java.awt.Color(153, 153, 153));
        deliveryButton.setText("Delivery");
        deliveryButton.setBorder(null);
        deliveryButton.setBorderPainted(false);
        deliveryButton.setContentAreaFilled(false);
        deliveryButton.setFocusPainted(false);
        deliveryButton.setFocusable(false);
        jPanel1.add(deliveryButton);
        deliveryButton.setBounds(430, 450, 250, 50);

        dealerButton.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        dealerButton.setForeground(new java.awt.Color(153, 153, 153));
        dealerButton.setText("Dealer");
        dealerButton.setBorder(null);
        dealerButton.setBorderPainted(false);
        dealerButton.setContentAreaFilled(false);
        dealerButton.setFocusPainted(false);
        dealerButton.setFocusable(false);
        jPanel1.add(dealerButton);
        dealerButton.setBounds(430, 350, 250, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/button_noClick.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 240, 260, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/bg2.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-280, -310, 1050, 790);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/bg.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(730, -20, 740, 730);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/button_noClick.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 340, 260, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/button_noClick.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 440, 260, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addAccountButtonListener(ActionListener listener) {
        accountButton.addActionListener(listener);
    }
    
    public void addDealerButtonListener(ActionListener listener) {
        dealerButton.addActionListener(listener);
    }
    
    public void addDeliveryButtonListener(ActionListener listener) {
        deliveryButton.addActionListener(listener);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountButton;
    private javax.swing.JButton dealerButton;
    private javax.swing.JButton deliveryButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
